### PR TITLE
Fix 121

### LINKED ISSUE #121: Uncaught ReferenceError with scala.js version 1.0.1
I updated my project to scala.js version 1.0.1 and got the following runtime exception in my browser console when instantiating an ActorSytem:

```
Uncaught ReferenceError: setImmediate is not defined
    at new $c_Lakka_dispatch_EventLoopExecutor (ExecutorServiceDelegate.scala:14)
    at $p_Lakka_dispatch_Dispatcher$LazyExecutorServiceDelegate__executor$lzycompute__ju_concurrent_ExecutorService (EventLoopExecutorConfigurator.scala:11)
    at $c_Lakka_dispatch_Dispatcher$LazyExecutorServiceDelegate.executor__ju_concurrent_ExecutorService (Dispatcher.scala:41)
    at $c_Lakka_dispatch_Dispatcher.registerForExecution__Lakka_dispatch_Mailbox__Z__Z__Z (ThreadPoolBuilder.scala:69)
    at $c_Lakka_dispatch_Dispatcher.attach__Lakka_actor_ActorCell__V (AbstractDispatcher.scala:156)
    at $f_Lakka_actor_dungeon_Dispatch__start__Lakka_actor_ActorCell (Dispatch.scala:116)
    at $c_Lakka_actor_ActorCell.start__Lakka_actor_ActorCell (ActorCell.scala:408)
    at $c_Lakka_actor_JSLocalActorRefProvider.init__Lakka_actor_ActorSystemImpl__V (ActorRef.scala:349)
    at $c_Lakka_actor_JSLocalActorRefProvider.init__Lakka_actor_ActorSystemImpl__V (JSLocalRefProvider.scala:106)
    at $p_Lakka_actor_ActorSystemImpl__liftedTree2$1__Lakka_actor_ActorSystemImpl (ActorSystem.scala:1035)
```

The following minimal setup reproduces the issue:

build.properties: 
```
sbt.version=1.3.9
```

plugins.sbt:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.1")
```

Main.scala: 
```scala
package core

import akka.actor.ActorSystem

object Main {
  def main(args: Array[String]): Unit = {
    val actorSystem = ActorSystem("System")
    println("This line won't get printed")
  }
}
```

build.sbt:
```sbt
val akkaJsVersion = "2.2.6.3"
lazy val root = (project in file("."))
  .enablePlugins(ScalaJSPlugin)
  .settings(
    name := "akka_js_test",
    scalaVersion := "2.13.1",
    scalaJSUseMainModuleInitializer := true,
    libraryDependencies ++= Seq(
      "org.akka-js" %%% "akkajsactor" % akkaJsVersion
    )
  )
```

and for startup the index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="akka_js_test-fastopt.js"></script>
  </head>
</html>
```

The problem doesn't occur with scala.js version "0.6.32".

### PR DESCRIPTION
**Pull request by andreaTP**
This fixes #121

### CODE REVIEW

File: akka-js-actor/js/src/main/scala/akka/dispatch/ExecutorServiceDelegate.scala [hunk 1]
```diff
@@ -11,7 +11,7 @@ class EventLoopExecutor extends ExecutorServiceDelegate {
   def executor: ExecutorService = this
 
   final val deferringFunction: Runnable => Unit =
-    if (js.isUndefined(global.setImmediate)) {
+    if (js.typeOf(global.setImmediate) == "undefined") {
```
Comment (alexandru) [inline akka-js-actor/js/src/main/scala/akka/dispatch/ExecutorServiceDelegate.scala]: A better check is `js.typeOf(global.setImmediate) == "function"` since you can pollute the global namespace with anything. Doesn't buy you much, but it is a little more idiomatic for JavaScript/TypeScript imo.

Comment (andreaTP) [reply akka-js-actor/js/src/main/scala/akka/dispatch/ExecutorServiceDelegate.scala]: make sense! This week is scheduled a new Akka release, I'm going to batch the fix and the upgrade there.
